### PR TITLE
scss-lint updates

### PR DESCRIPTION
**Pull request by stnvh**
This updates the gulp plugin to use a more well maintained, and quicker alternative - in-turn, needing the updated version of the gem:

If the output of `which gem` is `/usr/local/bin/gem`:
`gem update --system && gem uninstall scss-lint && gem install scss_lint`

else, `sudo` the lot!

------

I [wrote some regex](https://github.com/bigfork/SilverStripe-Shoelace/blob/dev/lint-updates/.scss-lint.yml#L133) for our BEM-ish selector format, rule is no more than one "element" or "modifier" e.g `.nav__item--active` & `.nav--green` is ok, but `.nav__item__cell--active` isn't. Also hyphens aren't allowed in the block or element bits, so `.nav-head__item` would also be invalid.
Thoughts? Anything that I've missed?

### CODE REVIEW

**Comment by kinglozzer** [comment]
Looks okay to me, comments below:

> `gem uninstall scss-lint`

Will this affect old sites if we need to update + compile something in them? If so, can we leave the old one installed?

I’d probably leave the selector linting disabled. We get some selectors we can’t control (\*cough\* SilverStripe forms \*cough\*), and sometimes it’s convenient to do non-BEM-ish stuff for utility classes. If we are going to enable it, could we not use the `hyphenated_BEM` one that’s bundled with scss-lint? Hyphens should be allowed in any of block/element/modifier - `.lang-switcher__lang-icon--extra-large` is valid BEM

**Comment by stnvh** [comment]
I don't think you can run them parallel, as ruby translates underscores to hyphens for program names. Should an old site need to be updated, just comment out the linter in the gulp/grunt file - we use our current setup a lot more than updating older sites!

I'll disable the selector format for now. The regex could be changed to account for util classes, though they'd need to follow a common pattern or something e.g begin with a certain character. Forms would be even more tricky - not worth it!

**Comment by stnvh** [comment]
Thinking of it, there would be a way to keep both with some `$PATH` botchery - a small script to append/remove a location to `$PATH` where the older binary is located.

**Comment by stnvh** [comment]
I've worked around the problem with a wrapper script. The script shims a 'legacy' gem install location for the older version, and dynamically selects a version at runtime. It will install the legacy stuff for you.

Make sure you're using ruby from brew, place this in `~/bin` named `scss-lint`, and ensure the path is exported (~/.bash_profile: `export PATH=$HOME/bin:$PATH`).

```bash
#!/bin/bash

# not a brilliant test - this is how gulp-scsslint (legacy) invokes the script
if [[ "$1" -eq "-c" ]]; then
	if [[ ! -d "$HOME/bin/legacygems" ]]; then
		mkdir "$HOME/bin/legacygems"
	fi

	export GEM_HOME="$HOME/bin/legacygems"

	GEMS="$(gem env gemdir)/gems"
	EXEC=("$GEMS"/scss-lint*/bin/scss-lint)

	if [[ ! -f "$EXEC" ]]; then
		gem install scss-lint
	fi
else
	GEMS="$(gem env gemdir)/gems"
	EXEC=("$GEMS"/scss_lint*/bin/scss-lint)
fi

exec "$EXEC" "$@"
```

**Pull request closed without merging**
